---
  - name: Update apt-cache
    apt: update_cache=yes 

  - name: Install curl
    apt: 
      name:   ['curl']
      state: latest

  - name: set apt sources
    shell: curl -sL https://deb.nodesource.com/setup_19.x | sudo bash -

  - name: Install nodejs
    apt: 
      name:   ['nodejs']
      state: latest

  - name: install useful node-related tools
    shell: npm install -g bower pm2 pm2-logrotate pino-pretty forever pm2-metrics
