---
- name: Setup and build Node.js app
  hosts: jsbc      # 👈 adjust to your inventory group/host
  become: yes

  vars:
    node_version: "12.16.0"
    project_path: "/opt/myapp"
    remove_source: true   # set to false if you want to keep source

  roles:
    - node_setup
